# SPDX-License-Identifier: CC0-1.0
---
name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  reuse-compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5
