# SPDX-FileCopyrightText: 2025 GSI Helmholtzzentrum für Schwerionenforschung GmbH <https://www.gsi.de/en/>
#
# SPDX-License-Identifier: CC0-1.0

---
name: Go

on: [push, pull_request]

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24']
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Setup gotestsum
      uses: autero1/action-gotestsum@v2.0.0
      with:
        gotestsum_version: 1.12.2

    - name: Download dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: gotestsum --junitfile junit-report.xml -- -cover ./...

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: (success() || failure()) && matrix.go-version == '1.24'
      with:
        report_paths: 'junit-report.xml'

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24']
        goos: [linux]
        goarch: [amd64]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Download dependencies
      run: go mod download

    - name: Build Debug
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        go build -buildvcs=true -v ./cmd/bmctl

    - name: Upload build artifacts
      if: matrix.go-version == '1.24'
      uses: actions/upload-artifact@v4
      with:
        name: bmctl-${{ matrix.goos }}-${{ matrix.goarch }}-debug
        path: |
          bmctl*
        retention-days: 30

  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.24']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run golangci-lint (includes gofumpt)
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest
